import type { Table } from '../classes/table.ts';

/**
 * The `EntityTable` family -- typing for records whose primary key is
 * generated by the store.
 *
 * `interface Friend { id: number; name: string }` is what a READ returns, but
 * `db.friends.add({ name })` must not have to fake an `id`. `EntityTable<Friend,
 * 'id'>` says both things: reads are `Friend`, the key is `Friend['id']`, and
 * inserts are `Friend` with `id` optional and methods omitted. Same shape and
 * names as Dexie 4, so a migrated declaration file compiles as it is.
 */

type IsStrictlyAny<T> = (T extends never ? true : false) extends false
    ? false
    : true;

/** Properties that never come from the caller on insert: methods. */
export type NonInsertProps<T> = {
    [P in keyof T]: IsStrictlyAny<T[P]> extends true
        ? never
        : T[P] extends (...args: any[]) => any
          ? P
          : never;
}[keyof T];

/**
 * `T` as it is inserted: the given props (an auto-generated key, typically)
 * become optional and methods are dropped.
 */
export type InsertType<T, OptionalProps extends keyof T> = Omit<
    T,
    OptionalProps | NonInsertProps<T>
> & {
    [P in OptionalProps]?: T[P];
};

/**
 * The key type: if `TKeyPropNameOrKeyType` names a property of `T`, that
 * property's type; otherwise it is taken to be the key type itself.
 */
export type IDType<T, TKeyPropNameOrKeyType> =
    IsStrictlyAny<T> extends true
        ? TKeyPropNameOrKeyType
        : TKeyPropNameOrKeyType extends string
          ? TKeyPropNameOrKeyType extends keyof T
              ? T[TKeyPropNameOrKeyType]
              : TKeyPropNameOrKeyType
          : TKeyPropNameOrKeyType;

/**
 * A table of `T` keyed on the property `TKeyPropName`, which the store
 * generates and the caller may therefore omit on insert.
 */
export type EntityTable<
    T,
    TKeyPropName extends keyof T = never,
    TInsertType = InsertType<T, TKeyPropName>,
> = Table<T, IDType<T, TKeyPropName>, TInsertType>;
