//Expo's own ignore list rather than the generic node one the browser
//templates use - there is no esbuild output to enumerate, and most of what
//needs ignoring here (native projects, metro caches, signing keys) does not
//exist in a browser project at all.
//
///ios and /android are ignored because they are generated by "npx expo
//prebuild" and are regenerated from app.json. Delete those two lines if you
//switch to a bare workflow and start editing native code by hand.
export default function genExpoGitIgnore() {
    const tpl = `
# dependencies
node_modules/

# Expo
.expo/
dist/
web-build/
expo-env.d.ts

# Native
.kotlin/
*.orig.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision

# Metro
.metro-health-check*

# debug
npm-debug.*
yarn-debug.*
yarn-error.*

# macOS
.DS_Store
*.pem

# local env files
.env*.local

# typescript
*.tsbuildinfo

# generated native folders
/ios
/android
`;

    return tpl;
}
