import type { Opts, Template } from "./cli.js";

//esbuild writes its output into public/ alongside the handwritten
//index.html / manifest.json, so those generated files have to be listed one
//by one - the folder itself must stay tracked. The vite and next templates
//own their output directory outright and can ignore it wholesale.
//
//Keyed on the full Template union rather than a subset, so that adding a
//template to TEMPLATES fails to compile until its build output is declared.
//expo's row is empty because it never calls this - it has its own ignore
//file, see genExpoGitIgnore.ts - but it is listed to keep that guard total.
const OUTPUT: Record<Template, string[]> = {
    react: ["apps/web/public/app.js", "apps/web/public/app.css", "apps/web/public/*.map"],
    pwa: [
        "apps/web/public/app.js",
        "apps/web/public/app.css",
        "apps/web/public/sw.js",
        "apps/web/public/*.map",
    ],
    extension: [
        "apps/extension/public/popup.js",
        "apps/extension/public/popup.css",
        "apps/extension/public/content.js",
        "apps/extension/public/background.js",
        "apps/extension/public/*.map",
    ],
    expo: [],
    "vite-spa": ["apps/web/dist"],
    "rsbuild-spa": ["apps/web/dist"],
    "next-drizzle": [
        "apps/web/.next",
        "apps/web/out",
        "apps/web/next-env.d.ts",
        "apps/web/*.db",
        "apps/web/*.db-journal",
        ".env*.local",
    ],
    "fastify-react": ["apps/web/dist", "apps/server/dist"],
};

//with --tailwind the stylesheet imported by the app is compiled from
//src/styles.css by the tailwind CLI, so it stops being a source file and must
//not be committed. null for the templates that compile tailwind through a
//bundler plugin instead: there is no intermediate stylesheet on disk.
const TAILWIND_OUTPUT: Record<Template, string | null> = {
    react: "apps/web/src/app.css",
    pwa: "apps/web/src/app.css",
    extension: "apps/extension/src/popup.css",
    expo: null,
    "vite-spa": null,
    "rsbuild-spa": null,
    "next-drizzle": null,
    "fastify-react": null,
};

export default function genGitIgnore(o: Opts) {
    const generated = [...OUTPUT[o.template]];
    const compiled = TAILWIND_OUTPUT[o.template];

    if (o.tailwind && compiled) {
        generated.push(compiled);
    }

    const output = generated.join("\n");

    const tpl = `
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# build output
${output}
`;

    return tpl;
}
