//A cache-first app shell, hand-written rather than generated by workbox - it
//is short enough to read, and reading it is the point.
//
//Two things it deliberately does NOT do: no runtime caching of cross-origin
//requests, and no update prompt. skipWaiting + clients.claim mean a new
//worker takes over as soon as it is installed; the trade-off is that a page
//can briefly hold assets from two versions.
//
//Bump VERSION to invalidate everything - the activate handler deletes every
//cache that is not the current one.
export default function genSwTs() {
    const tpl = `
/// <reference lib="webworker" />

//narrows the global from WorkerGlobalScope, which is what lib.webworker
//declares "self" as, to the service worker flavour that has skipWaiting()
declare const self: ServiceWorkerGlobalScope;

const VERSION = "v1";
const SHELL = "shell-" + VERSION;

//cache.addAll is all-or-nothing: one 404 here fails the install and the
//worker never activates, silently. Keep this in step with the build output.
const ASSETS = [
    "/",
    "/index.html",
    "/app.js",
    "/app.css",
    "/icon.svg",
    "/icon-192.png",
    "/manifest.webmanifest",
];

function fetchAndCache(req: Request) {
    return fetch(req).then((res) => {
        //the body can only be read once, so cache a copy and return the original
        const copy = res.clone();
        caches.open(SHELL).then((cache) => cache.put(req, copy));
        return res;
    });
}

self.addEventListener("install", (e) => {
    e.waitUntil(
        caches
            .open(SHELL)
            .then((cache) => cache.addAll(ASSETS))
            .then(() => self.skipWaiting()),
    );
});

self.addEventListener("activate", (e) => {
    e.waitUntil(
        caches
            .keys()
            .then((keys) =>
                Promise.all(keys.filter((k) => k !== SHELL).map((k) => caches.delete(k))),
            )
            .then(() => self.clients.claim()),
    );
});

self.addEventListener("fetch", (e) => {
    const req = e.request;

    //POSTs and cross-origin requests fall through to the network untouched
    if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) {
        return;
    }

    //navigations go to the network first so a deploy is picked up on reload,
    //and fall back to the cached shell when offline
    if (req.mode === "navigate") {
        e.respondWith(
            fetch(req).catch(() =>
                caches.match("/index.html").then((hit) => hit ?? Response.error()),
            ),
        );
        return;
    }

    e.respondWith(caches.match(req).then((hit) => hit ?? fetchAndCache(req)));
});

//isolatedModules treats a file with no import or export as a global script
export {};
`;

    return tpl;
}
