<script lang="ts">
	import type { Snippet } from 'svelte';

	// A body row. Separated from DataTable rather than generated by it so the
	// caller keeps the things that genuinely differ per row — a click handler, a
	// selected//muted state, a conditional tint — which a `rows`-driven table
	// could only express by growing a prop for each of them.

	let {
		selected = false,
		class: className = '',
		onclick,
		children,
		...rest
	}: {
		selected?: boolean;
		class?: string;
		onclick?: (event: MouseEvent) => void;
		children: Snippet;
		/** Anything else (title, aria-*, data-*) lands on the element. */
		[key: string]: unknown;
	} = $props();
</script>

<tr
	{...rest}
	class="sak-tr {className}"
	class:sak-tr-selected={selected}
	class:sak-tr-clickable={onclick}
	{onclick}
>
	{@render children()}
</tr>

<style>
	.sak-tr {
		border-top: 1px solid var(--sak-table-border, #e2e8f0);
	}

	.sak-tr-clickable {
		cursor: pointer;
	}

	.sak-tr-clickable:hover,
	.sak-tr-selected {
		background: var(--sak-table-row-hover, #f8fafc);
	}
</style>
